### ISSUE TITLE
riemann-health:  NoMethodError undefined method `map' for #<Riemann::Event:0x000000024c9e90>

### ISSUE THREAD

**Issue by joelapatatechaude** [riemann/riemann#506]
When trying to follow the quickstart guide I get the error
NoMethodError undefined method `map' for #<Riemann::Event:0x000000024c9e90>
at the very beginning of riemann-health execution

I get a similar error when trying to log an HTTP request manually with the ruby client.

For info
I am running Fedora 21
Using the tar version of Riemann: riemann-0.2.8

My local ruby are:
[chris@localhost ~]$ gem list

*** LOCAL GEMS ***

beefcake (1.1.0.pre1)
bigdecimal (1.2.4)
builder (3.2.2)
CFPropertyList (2.3.0)
erubis (2.7.0)
excon (0.44.1)
faraday (0.9.1)
fission (0.5.0)
fog (1.27.0)
fog-atmos (0.1.0)
fog-aws (0.0.8)
fog-brightbox (0.7.1)
fog-core (1.28.0)
fog-ecloud (0.0.2)
fog-json (1.0.0)
fog-profitbricks (0.0.1)
fog-radosgw (0.0.3)
fog-sakuracloud (1.0.0)
fog-serverlove (0.1.1)
fog-softlayer (0.4.0)
fog-storm_on_demand (0.1.0)
fog-terremark (0.0.3)
fog-vmfusion (0.0.1)
fog-voxel (0.0.2)
fog-xml (0.1.1)
formatador (0.2.5)
inflecto (0.0.2)
io-console (0.4.2)
ipaddress (0.8.0)
json (1.8.1)
mime-types (2.4.3)
mini_portile (0.6.2)
mtrc (0.0.4)
multi_json (1.3.6)
multipart-post (2.0.0)
munin-ruby (0.2.5)
net-scp (1.2.1)
net-ssh (2.9.3.beta1)
nokogiri (1.6.6.2)
psych (2.0.5)
rack (1.6.0)
rack-protection (1.5.3)
rdoc (4.1.1)
riemann-client (0.2.3)
riemann-dash (0.2.10)
riemann-tools (0.2.5)
sass (3.4.10)
sinatra (1.4.5)
tilt (1.4.1)
trollop (2.1.1)
webrick (1.3.1)
yajl-ruby (1.2.1)

My ruby stuff installed with yum are:

[root@localhost chris]# rpm -qa | grep ruby
rubygem-io-console-0.4.2-26.fc21.x86_64
rubygem-json-1.8.1-26.fc21.x86_64
ruby-devel-2.1.5-26.fc21.x86_64
rubygem-psych-2.0.5-26.fc21.x86_64
ruby-libs-2.1.5-26.fc21.x86_64
rubygems-2.2.2-101.fc21.noarch
rubygem-bigdecimal-1.2.4-26.fc21.x86_64
ruby-irb-2.1.5-26.fc21.noarch
ruby-2.1.5-26.fc21.x86_64
rubypick-1.1.1-2.fc21.noarch
rubygem-rdoc-4.1.1-2.fc21.noarch

[root@localhost chris]# uname -a
Linux localhost.BigPond 3.17.7-300.fc21.x86_64 #1 SMP Wed Dec 17 03:08:44 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aphyr** [comment]
I think you've fallen victim to a bug/unintentional API change/something in Beefcake we may have fixed in riemann-client 0.2.4. If you upgrade that gem it may fix your problem.

**Comment by joelapatatechaude** [comment]
Updated it:
[chris@localhost riemann-0.2.8]$ gem list | grep riem
riemann-client (0.2.4)
riemann-dash (0.2.10)
riemann-tools (0.2.5)

Still the same problem :(

Does it mean that I can't use riemann at all, or does it just mean that I can't interact with it with ruby related tools / interfaces?

**Comment by aphyr** [comment]
Naw, this is strictly a ruby client issue. @peterneubauer and @pschrammel fought this issue with Ruby 2.1.x and newer Beefcake versions--I thought we had it fixed, but I may have messed up the release, or you may be including a newer Beefcake version anyway. Can you see upgrading to riemann-client 0.2.5, or forcing the use of Beefcake <= 1.0.0, fixes your problem?

https://github.com/aphyr/riemann-tools/issues/103

**Comment by joelapatatechaude** [comment]
riemann-client 0.2.5 didn't solve the issue.
Downgrading to beefcake 1.0.0 made the problem disappear.
Thanks!
In the meanwhile, I am available to test new riemann versions if necessary

**Comment by aphyr** [comment]
Righto, I think we're gonna have to wait for Beefcake to release a fix then. :(
